### ISSUE TITLE
Issue compiling with sbcl 2.1.9

### ISSUE THREAD

**Issue by vi1** [scymtym/parser.common-rules#2] opened 2021-10-14 15:12 UTC
I'm not even sure what it tells me. Too busy to figure out.Sorry.

**Comment by scymtym** [comment] 2021-10-15 10:27
The problem likely is that the version of [esrap](https://github.com/scymtym/esrap) which is available via Quicklisp does not work with SBCL 2.1.9. The problem is fixed in the esrap master branch. Until the next Quicklisp release, manually switching to esrap master is the only solution I can think of.

**Comment by vi1** [comment] 2021-10-16 12:53
Oh, thank you! It does indeed work. Thanks for maintaining it. Esrap is great stuff!

**Closed as completed** 2021-10-18 11:31 UTC
